---
abstract: 'A Template Plugin to Profile Template'
author:
  - 'Kentaro Kuribayashi <kentaro@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: MIT
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-Timer
no_index:
  directory:
    - inc
    - t
requires:
  Benchmark::Timer: 0
  Template: 0
version: 0.01
